### PR TITLE
Remove HashTag check as it is not universally observed

### LINKED ISSUE #107: (Optionally?) skip HashTag quick test on verification
As discussed at https://mailarchive.ietf.org/arch/msg/openpgp/Zv8v1IwbbXYiDPKytfbUmtNdxak/ and https://github.com/hockeypuck/hockeypuck/issues/187#issuecomment-1178040968 , it appears that go-crypto is in the minority of implementations that fast-fails on the HashTag test at https://github.com/ProtonMail/go-crypto/blob/5afb4c282135d8a2642d460e4089f8bd55b3e171/openpgp/packet/public_key.go#L614 :

```
	hashBytes := signed.Sum(nil)
	if hashBytes[0] != sig.HashTag[0] || hashBytes[1] != sig.HashTag[1] {
		return errors.SignatureError("hash tag doesn't match")
	}
```

Several known keys in the wild fail on this test yet successfully validate in other implementations, including GnuPG and Sequoia.

While go-crypto is technically correct here, the fast-fail test is not required by the standard and is sufficiently broken elsewhere that its usefulness is questionable.

### PR DESCRIPTION
**Pull request by andrewgdotcom**
closes #107

### CODE REVIEW

**Comment by harrycguo** [comment]
@twiss Hi! Is there an update on the status of this PR?

**Comment by twiss** [comment]
Hey :wave: At IETF 114, there was a poll about this issue, as documented [here](https://gitlab.com/openpgp-wg/rfc4880bis/-/issues/143):

> "should we state that implementations MUST reject signatures (v4 or v5) with incorrect signature checksums?" this was supported by 9 and opposed by 1

So, it seems the consensus is in favor of keeping this check. Of course, it can be discussed further on the mailing list, but if consensus stays that way, I think it's unlikely we'll merge this, tbh.

**Comment by harrycguo** [comment]
Got it, thank you so much for the answer and linking the discussion!

**Comment by andrewgdotcom** [comment]
New PR is #165

**Pull request closed without merging**
