### PR TITLE
add  AddUserId , support UserAttribute, 

### PR DESCRIPTION
**Pull request by izouxv**
create a AddUserId function in Entity struct

### CODE REVIEW

**Comment by izouxv** [comment]
Hi
I add a addUserId api, and support userAttrbute veriable in Entitly, 
it will support photo in the keys, and compatible with openpgp 2.3.6

please take some time merging 
thank you.

**Comment by twiss** [comment]
Hi :wave: Thanks for the PR! However, the PR seems to be doing 3 quite separate things (adding user IDs, support for user attributes, and compatibility with GnuPG 2.3). Could you make separate PRs for each, please? And also, could you elaborate on what the issue with GnuPG 2.3 is, and what the workaround does? Has the issue been reported in GnuPG? Etc.

**Comment by izouxv** [comment]
done

**Comment by twiss** [comment]
Closing in favor of #125 and #126.

**Pull request closed without merging**
